workflows:
  cordova-android:
    name: Cordova Android Workflow
    environment:
      node: latest
      java: latest
      # android: latest
    scripts:
      - name: Install Dependencies
        script: |
          npm install
          npm ci
      - name: Add Android Platform
        script: |
          cordova platform add android
      - name: Build APK
        script: |
          cordova build android
      # - name: Sign APK
      #   script: |
      #     jarsigner \
      #       -sigalg SHA1withRSA \
      #       -digestalg SHA1 \
      #       -keystore $CM_KEYSTORE_PATH \
      #       -storepass $CM_KEYSTORE_PASSWORD \
      #       -keypass $CM_KEY_PASSWORD \
      #       platforms/android/app/build/outputs/apk/release/app-release-unsigned.apk \
      #       $CM_KEY_ALIAS
      #     $ANDROID_HOME/build-tools/30.0.3/zipalign \
      #       -v 4 \
      #       platforms/android/app/build/outputs/apk/release/app-release-unsigned.apk \
      #       app-release.apk
      - name: Upload APK
        script: |
          echo "Deploying app to Codemagic..."
          curl -v -X POST \
            -F "file=@app-release.apk" \
            -H "x-auth-token: $CM_API_TOKEN" \
            -H "content-type: multipart/form-data" \
            https://api.codemagic.io/artifacts/upload
    artifacts:
      - app-release.apk
